### ISSUE TITLE
allow a `className` propType to pass-through directly to the canvas element

### ISSUE THREAD

**Issue by matyus** [alampros/react-confetti#11]
It would be nice if I could do this:

```jsx
<Confetti className="foo" />
```
so that the rendered DOM element ends up like this:

```html
<canvas class="foo"></canvas>
```

(I'm happy to submit a PR if you're open to it.)

**Comment by alampros** [comment]
Oops - good call! It should definitely pass props through. I'm definitely open to a PR. Thanks!
