### ISSUE TITLE
import { Confetti as FooConfetti } from "react-confetti"

### ISSUE THREAD

**Issue by matyus** [alampros/react-confetti#12]
It would be nice if I could alias the component name on import:

```jsx
import { Confetti as ReactConfetti } from "react-confetti"
```

The reason is that I'd like to wrap this component in my own proprietary component, called `Confetti`, but I obviously can't `import Confetti` in a class that I've also named `Confetti`.

This is the error I get:
<img width="683" alt="screen shot 2017-05-10 at 8 12 27 pm" src="https://cloud.githubusercontent.com/assets/1214020/25926417/0e373b12-35bd-11e7-94c4-637c30602cce.png">

(I'm happy to submit a PR if you're open to it.)

**Comment by alampros** [comment]
You don't need to change anything for this to work. You just use whatever local variable name you want and the default export gets assigned to it. 

```js
Import FooConfetti from 'react-confetti'
```

Should work just fine.
