### ISSUE TITLE
How can I run it once every time I click on a button?

### ISSUE THREAD

**Issue by ImSolitude** [alampros/react-confetti#120]
I'm just trying to implement this Logic:

I have a button, I want to run this confetti *every time* I click on the button for just once, Why is it hard to implement, been tying for 1 hour!

**Comment by alampros** [comment]
I'm sorry you're frustrated with this free software I provided out of sheer altruism.

You can first try looking thru [the docs](https://alampros.github.io/react-confetti/?path=/story/props-demos--party)...or the [closed issues](https://github.com/alampros/react-confetti/issues/114#issuecomment-908588925).
