### ISSUE TITLE
Exploding effect

### ISSUE THREAD

**Issue by jahirfiquitiva** [alampros/react-confetti#129]
Hi

I am wondering if you could help me or guide me on how I can achieve an exploding effect similar to the one shown in [this StoryBook](https://ulitcos.github.io/react-canvas-confetti/playground/index.html?path=/story/realistic--realistic-story)

Thanks in advance!

**Comment by MattHalloran** [comment]
@jahirfiquitiva Did you ever figure this out? I would like to do the same thing.

**Comment by alampros** [comment]
Sorry for the delayed response. Off the top of my head, I would start by trying to animate the `confettiSource` property. I would probably reach for [framer/motion](https://www.framer.com/motion/) or [react-spring](https://react-spring.io/) to handle the animation nicely.

Good luck!

**Comment by thiago-tallison** [comment]
@jahirfiquitiva you can just use something like this:

```jsx
<Confetti
  confettiSource={{
    x: center.x,
    y: center.y,
  }}
  run={true}
  recycle={false}
  numberOfPieces={numberOfPieces}
  initialVelocityX={15}
  initialVelocityY={30}
  gravity={0.3}
  onConfettiComplete={() => setNumberOfPieces(0)}
  tweenDuration={1}
/>
```

The `recycle` property prevents the effect from repeating, and `tweenDuration` does the magic: it launches all the confetti at the same time, creating an exploding effect.
