### ISSUE TITLE
How to disable black bar on top

### ISSUE THREAD

**Issue by joevo2** [alampros/react-confetti#13]
When over scroll up i can see the top black bar, how can i disable it or set it transparent? 

![Image](http://i.imgur.com/IxngfOQ.jpg)

**Comment by alampros** [comment]
I think this is caused by sub-pixel sizing (if the canvas' dimensions are set to a non-integer). I'll check it out.

**Comment by alampros** [comment]
@joevo2 - I just published `v2.0.0-beta1` to npm. You can test it by installing the `beta` `dist-tag`:

```sh
yarn add react-confetti@beta
```

**Comment by joevo2** [comment]
The black bar is gone but the width and height doesnt seems to be working. Even if i put in width=100% it doesnt work 
![Screenshot](http://i.imgur.com/dgdgMUf.png)

**Comment by joevo2** [comment]
I think the issues start from 1.1.5 in 1.1.4 is still ok

**Comment by alampros** [comment]
@joevo2 I think this is because the `width` and `height` props are now required. See the [demo example](https://github.com/alampros/react-confetti/blob/v2.0.0-beta1/src/docs.jsx) for how to provide it with a HOC.

Let me know if that doesn't solve the issue.

**Comment by alampros** [comment]
@joevo2 I've updated the [docs](https://github.com/alampros/react-confetti/blob/develop/README.md) to reflect this

**Comment by joevo2** [comment]
Awesome 👏 it works perfectly now. The example in the readme might be a bit Intimidating for beginner 😊
