### ISSUE TITLE
Confetti does not work in Brave browser

### ISSUE THREAD

**Issue by macmartine** [alampros/react-confetti#149]
In Brave browser, this just displays as a static horizontal row of confetti that's always there.

**Comment by yahyashareef48** [comment]
it's working

**Comment by gabrielduete** [comment]
It's workig for me.

Maybe you need configure props to disable when you need?

**Comment by ryancwalsh** [comment]
It works for me in Brave.

**Comment by keremesen** [comment]
Its working for me too

**Comment by alampros** [comment]
I think Brave is chromium based, so it would make sense that it works like other browsers. Sounds like this is an implementation issue.
