### ISSUE TITLE
React Confetti Causes horizontal scroll 

### ISSUE THREAD

**Issue by anasmohammed361** [alampros/react-confetti#154]
[Screencast from 2024-01-25 13-18-37.webm](https://github.com/alampros/react-confetti/assets/78010612/99e2057f-b553-4561-9a80-ae1e0bf6c441)

**Comment by anasmohammed361** [comment]
```
"use client";

import ReactConfetti from "react-confetti";
import { useConfettiStore } from "../hooks/useConfettiStore";

export const ConfettiProvider = () => {
  const confetti = useConfettiStore();
  if (!confetti.isOpen) return null;
  return (
     <ReactConfetti
      className="pointer-events-none z-[100]"
      numberOfPieces={500}
      recycle={false}
      onConfettiComplete={() => {
        confetti.onClose();
      }}
    />
  )
}
```
this is my react component , i use zustand for the custom hook but that should n't be causing any issue for the most part i guess

**Comment by bonface221** [comment]
@anasmohammed361  have you tried wrapping that component in a div maybe and add overflow hidden and w='100%' ?
or w='100vw'

**Comment by anasmohammed361** [comment]
Yes @bonface221 using `w=100%` fixed this issue . Thanks.
