### ISSUE TITLE
Change z-index of confetti

### ISSUE THREAD

**Issue by guilhermesad** [alampros/react-confetti#156]
Is there an easy way to change the z-index of the confetti? Currently it gets behind the [Flatfile Widget](https://flatfile.com/) we're using in our application.

**Comment by j0hnm4r5** [comment]
I think you can just provide it a `zIndex` via the `style` prop.

```jsx
<Confetti style={{ zIndex: 9999 }} />
```

**Comment by guilhermesad** [comment]
@j0hnm4r5 I tried that but didn't work unfortunately

**Comment by combokitnet** [comment]
> I think you can just provide it a `zIndex` via the `style` prop.
> 
> ```js
> <Confetti style={{ zIndex: 9999 }} />
> ```

It work for me

**Comment by alampros** [comment]
@j0hnm4r5 's solution should work fine, unless you're having trouble with mouse events. Might want to also add `pointer-events: none` to it.

```jsx
<Confetti style={{ zIndex: 9999, pointerEvents: 'none' }} />
```
