### ISSUE TITLE
Requires Object.assign polyfill for IE11

### ISSUE THREAD

**Issue by gragland** [alampros/react-confetti#16]
Should probably add babel-plugin-transform-object-assign to .babelrc. Happy to do a pull request for this if it's something you'd want to merge.

**Comment by alampros** [comment]
Browser support should be handled at a higher level (your project) than this component.

Thanks for mentioning this tho!

**Comment by alampros** [comment]
Browser support should be handled at a higher level (your project) than this component.

Thanks for mentioning this tho!
