### ISSUE TITLE
[Request] Start / Stop controls

### ISSUE THREAD

**Issue by arronhunt** [alampros/react-confetti#17]
Hey there,

For my particular needs, I'm trying to find a script that will only drop confetti for ~5 seconds and then stop generating new particles. It would be awesome to have a trigger to start and stop the effect.

**Comment by alampros** [comment]
Great idea - thanks! Could be controlled by a `run` prop.

**Comment by alampros** [comment]
I still need to document this, but you now (as of v2.0.0) have two options for controlling the run state:
1. **Using the `run` prop**: this will stop the render loop and freeze the confetti in place.
2. **Set `numberOfPieces` to `0`**: this will stop generating new confetti pieces and let the existing ones fall.

Hope this addresses your needs!

**Comment by Abhinav1190P** [comment]
Still can't stop it, i mean it stops at one place, that's the problem, some help please, i'm using a settimeout to set run to false and numberofpieces to 0.
