### ISSUE TITLE
Recycle doesn't work?

### ISSUE THREAD

**Issue by jezhou** [alampros/react-confetti#23]
Can't seem to get `recycle` to work. Flipping the flag to `false` perpetuates the animation loop when I believe it should stop after a certain amount of time.

Am I misunderstanding what the flag is for?

**Comment by alampros** [comment]
Yeah that may have been a casualty/regression of the last release (probably [this](https://github.com/alampros/react-confetti/blob/develop/src/confetti.js#L130)).

**Comment by alampros** [comment]
Fixed and released in `v2.0.1`

**Comment by jezhou** [comment]
@alampros thanks for the quick response!
