### ISSUE TITLE
width and height should default to full window size

### ISSUE THREAD

**Issue by ragesoss** [alampros/react-confetti#27]
This is a delightful component! I put it into my app for an impromptu celebration of my team hitting a milestone. :-)

I think it would be more useful it it defaulted to the full size of the window/browser, so that it can be tossed into an app without any config and provide confetti over the whole page.

`window.innerWidth` and `window.innerHeight` will probably work just fine.

**Comment by magician11** [comment]
I noticed that if I had scrolled way down a page, and activated the confetti run, I may not see it.

So for those wanting confetti to run down the entire document (including scrolling to the bottom) this works

`<Confetti height={document.body.scrollHeight} />`
