### ISSUE TITLE
Feature idea: a text banner

### ISSUE THREAD

**Issue by ragesoss** [alampros/react-confetti#28]
Just tossing this out as an idea: this component would be even cooler if you could provide a text prop, and it would show that text on some kind of banner that falls along with the confetti, so you can easily use it to celebrate specific things.

**Comment by ragesoss** [comment]
Here's the sort of thing I had in mind (only falling like the confetti, maybe?): https://codepen.io/danwilson/pen/PQddxe

**Comment by alampros** [comment]
Hah! That is awesome! I'd welcome a PR if you can do that banner in the canvas API.
