### ISSUE TITLE
Porting to React Native?

### ISSUE THREAD

**Issue by kennym** [alampros/react-confetti#32]
Are there plans to port this to React Native? If yes, is there a WIP? I'd like to help with that.

**Comment by alampros** [comment]
I have very little experience with RN, but I'd definitely take a PR!

**Comment by okcoker** [comment]
@kennym What exactly does RN need for this to work? A [separate canvas implementation](https://stackoverflow.com/questions/39972962/equivalent-of-canvas-in-react-native)? Maybe https://github.com/alampros/react-confetti/pull/36 would help in the meantime.

I'm personally using this in a chromecast app. The performance is pretty bad with just a 100 particles but that's another story. May have to look into altering the render loop for my case.
