### ISSUE TITLE
Implementing in Typescript project

### ISSUE THREAD

**Issue by AndreasNasman** [alampros/react-confetti#41]
Hi!

I'm having problem including the confetti in my project built with [create-react-app](https://github.com/facebook/create-react-app) using the `--typescript` flag. For some reason all props seem to be mandatory, since the defaults aren't taking into consideration. Am I including it correctly, or is Typescript not supported?

![image](https://user-images.githubusercontent.com/17124245/54531382-cbcdf680-498d-11e9-96b5-acaa1a5ebdcd.png)

**Comment by alampros** [comment]
Yikes! Sorry you're running into that. I'll take a look.

**Comment by alampros** [comment]
I've tested this locally with [v2.7.0](https://github.com/alampros/react-confetti/releases/tag/v2.7.0) and it's behaving much better.

Please re-open if you're still having trouble.

**Comment by AndreasNasman** [comment]
Thanks for the fix!

Is the idea that the package should work fully without installing a separate [@types ](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/) package or making a module declaration file? This isn't the case now, since it has an implicit _any_ type.
![image](https://user-images.githubusercontent.com/17124245/54677291-3eb0ac00-4b0b-11e9-9158-0d1d17bc2ee4.png)
![image](https://user-images.githubusercontent.com/17124245/54677309-4b350480-4b0b-11e9-827f-6532eded42fe.png)
