### ISSUE TITLE
Implicit 'any' type

### ISSUE THREAD

**Issue by AndreasNasman** [alampros/react-confetti#45]
Thanks for the fix!

Is the idea that the package should work fully without installing a separate [@types ](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/) package or making a module declaration file? This isn't the case now, since it has an implicit _any_ type.

![image](https://user-images.githubusercontent.com/17124245/54677291-3eb0ac00-4b0b-11e9-9158-0d1d17bc2ee4.png)
![image](https://user-images.githubusercontent.com/17124245/54677309-4b350480-4b0b-11e9-827f-6532eded42fe.png)

I bypassed this issue by creating my own _react-confetti.d.ts_ placeholder file, but that means no autocomplete or type completion.

_(I'm not privileged to reopen my original issue, so I'll reference it here)_

_Originally posted by @AndreasNasman in https://github.com/alampros/react-confetti/issues/41#issuecomment-474771895_

**Comment by alampros** [comment]
I think this is a regression from 3c3184c3e1fefff59f370eaaa16c887f48efe782.

I'll try to revert it and see if that helps.

**Comment by alampros** [comment]
@AndreasNasman - Can you try `v2.7.1` and see if it did the trick?

**Comment by AndreasNasman** [comment]
Works in 2.7.2 👍
