### ISSUE TITLE
Confetti not filling width

### ISSUE THREAD

**Issue by AndreasNasman** [alampros/react-confetti#46]
Not sure if this problem is caused by React, hooks, event listeners, or something else, but I'll mention it here for starters 🙂.

When defining a height and a width with `useState`, updating them with e.g. a resize event listener, and declaring the confetti-component with those state values as the **height** and **width** props, it seems like the spread of the confetti is bound to the previous width of the confetti-component.

As far as I can tell, this happens regardless of how the state variables are updated and doesn't seem to be device specific, as I tested it both in Chrome's and Firefox's mobile device simulation and on my phone.

I implemented the confetti-component to display a full screen confetti rain when a game ends on an application I made, and noticed this behaviour when flipping the screen from portrait to landscape. This is noticed easier when the difference between the height and width is greater.

![image](https://user-images.githubusercontent.com/17124245/54689073-7decf600-4b27-11e9-9768-9523dfa136a5.png)
![image](https://user-images.githubusercontent.com/17124245/54689152-a8d74a00-4b27-11e9-8bad-f89abacb6db0.png)
![image](https://user-images.githubusercontent.com/17124245/54689257-d3c19e00-4b27-11e9-9634-d907440eeedb.png)
_In portrait the confetti is spreading the whole width of the canvas..._
![image](https://user-images.githubusercontent.com/17124245/54687564-94458280-4b24-11e9-8388-e95cf6ced078.png)
_...but in landscape only 465px's (previous width) seems to be the spread._

[Screen Recording 2019-03-20 at 15.54.59.zip](https://github.com/alampros/react-confetti/files/2988524/Screen.Recording.2019-03-20.at.15.54.59.zip)

This can also be recreated by having e.g. a button expand the width by a large amount. The change is only visible after the second click, so I suspect the spread of the confetti is remembering the previous value.

I also tried this with `useWindowSize` from `react-use` and the same problem occurs.

**Comment by alampros** [comment]
I *think* by the looks of it that this is behaving as it should - the `confettiSource` Rect defaults to the width and height props, so no confetti is spawned yet in the empty areas in your screenshots. You could try passing in a custom `confettiSource` that would cover the width of your biggest dimensions.

If you let it run for a while, do they eventually start spawning into the empty areas?

**Comment by AndreasNasman** [comment]
> If you let it run for a while, do they eventually start spawning into the empty areas?
No, they area stays the same.

> You could try passing in a custom confettiSource that would cover the width of your biggest dimensions.
Thanks, that fixes my problem! 😊

**Comment by alampros** [comment]
Glad to hear!
