### ISSUE TITLE
Mobile performance worsens after multiple conditional renders

### ISSUE THREAD

**Issue by AndreasNasman** [alampros/react-confetti#47]
In my score tracking application where I've implemented the confetti rain I have it conditionally shown or hidden whether there is a winner or not. The winner can conditionally change on undo/redo or when a new game is started/completed.

![image](https://user-images.githubusercontent.com/17124245/54692512-cdcebb80-4b2d-11e9-8698-a60ffe48f69e.png)

What I've noticed is that the performance of the confetti worsens quite significantly after each re-render. From what I've tried, it's not really noticeable on desktop, but on a mobile browser you can definitively see the drop in performance. I tested this on my phone's Chrome and Firefox browser and it occurs in both.

Could there maybe be a memory leak somewhere? Something that isn't cleaned up in `componentDidUnmount`?

I bypassed this temporarily by conditionally hiding the component with `display: none;`, which works, but then you loose the confetti 'drop-in' animation, which is really pleasing if you ask me  😉.
![image](https://user-images.githubusercontent.com/17124245/54692714-1f774600-4b2e-11e9-9709-130d672e9e9c.png)

**Comment by alampros** [comment]
Yup - looks like there's a memory leak. Let me see if I can replicate it locally.

**Comment by AndreasNasman** [comment]
Problem still occurs in 2.7.2. Tested with Chrome's _mobile_ browser.

**Comment by alampros** [comment]
😫

I have another idea that might be of help - I’ll try adding a `destroy` method to stop the requestAnimationFrame loop before unmount.

**Comment by alampros** [comment]
@AndreasNasman - let me know if this actually fixed it.

**Comment by alampros** [comment]
Closing this for now. Let me know if this is still an issue in `>2.7.3`.
