### ISSUE TITLE
Laser show glitchy rendering

### ISSUE THREAD

**Issue by Mesoptier** [alampros/react-confetti#56]
In the latest Chrome version (`Version 75.0.3770.100 (Official Build) (64-bit)`) the confetti started glitching: https://youtu.be/CXxU2OQEzZg. 

Now, we've been calling it a feature ("laser show!") not a bug, but still.

It works fine in other browsers.

**Comment by VisheshSingh** [comment]
I am on the same version of Chrome as yours. I haven't noticed this today.

**Comment by alampros** [comment]
> Now, we've been calling it a feature ("laser show!") not a bug, but still.

☝️ 🤣 

Sorry to hear it was freakin out on you. I'm running that same version of chrome (mac) and I'm not seeing it. What OS are you on? Do you see it happening on the [storybook demo pages](https://alampros.github.io/react-confetti/)?

**Comment by alampros** [comment]
Just tested on windows and not seeing it either. That is super odd.

**Comment by Mesoptier** [comment]
> Sorry to hear it was freakin out on you. I'm running that same version of chrome (mac) and I'm not seeing it. What OS are you on? Do you see it happening on the [storybook demo pages](https://alampros.github.io/react-confetti/)?

We're running on Ubuntu. But I don't see it happening in the storybook, so it's probably something on our end. I'll try to reproduce it outside our product and get back to you.

**Comment by alampros** [comment]
FYI, I just published a new version ([v3.1.1](https://github.com/alampros/react-confetti/releases/tag/v3.1.1)) with a ton of dependency updates which *might* effect this issue.

**Comment by Mesoptier** [comment]
Yeaaaah, we were running `v2.0.0-beta1`. :sweat_smile:
I had just assumed we were running the latest version, it works fine after upgrading. I did see another "laser beam" again once or twice in `v3.1.0`, but they're exceedingly rare now (as in, I haven't been able to record one). Anyway, it's fixed now (already in `v3.1.0` btw), thanks!

**Comment by alampros** [comment]
Glad to hear!

Although, I might have to add a new "laser show" feature now...

**Comment by alampros** [comment]
> It doesn't happen on storybook.
@jesspoemape - can you tell me a bit about where it *does* happen? What kind of app? How are you providing the dimensions to the component?
