### ISSUE TITLE
Weird flickering when not recycling

### ISSUE THREAD

**Issue by Katli95** [alampros/react-confetti#60]
Hey man, love the Component!

I am however experiencing small problems when I switch recycling off, the confetti flickers after recycling is set to false :/ I tried getting a vid of it but my screen recorder (PowerPoint) didn't pick it up. Any ideas?

### Code
```javascript
<Confetti
            width={this.state.width}
            height={this.state.height}
            gravity={0.06}
            style={{ pointerEvents: "none" }}
            confettiSource={{ x: 0, y: -10, w: this.state.width, h: 4 }}
            recycle={this.state.spawnConfetti}
            onConfettiComplete={() => { this.setState({ shouldShowConfetti: false }); }}
/>
```
### Env. Info
|System|Version|
|---|---|
|`react` & `react-dom`|16.7.0|
|`react-confetti`|v3.1.2|
|Chrome|Version 75.0.3770.100 (Official Build) (64-bit)|
|Windows|Windows 10 Pro 1809 (64-bit) |

**Comment by alampros** [comment]
Sorry to hear - sadly I don't have a windows machine to test on. Does it flicker when you toggle the recycle flag using the knobs on the [demo site](https://alampros.github.io/react-confetti/)?

**Comment by Katli95** [comment]
Yeah they do :/ oddly enough. They also seem to be spinning faster once I've disabled the recycling, not sure if it is related but they most definitely do flicker a bit, not all of them mind you but enough of them to make it noticeable.
