### ISSUE TITLE
Glitch like laser with v2.4.1 only on Chrome browser

### ISSUE THREAD

**Issue by VisheshSingh** [alampros/react-confetti#61]
Hi, 

I am experiencing a glitchy behavior [for v2.4.1] only on the Chrome browser, wherein I see kind of a laser show. The reason why I am using v2.4.1 is that I am using React v15 which does not support createRefs or forward Refs. I am aware that the latest version of react-confetti has taken care of this but I am wondering if there is any patch for the issue I am facing.

Thanks

**Comment by alampros** [comment]
What browser version and OS are you on?

**Comment by VisheshSingh** [comment]
I am using Windows 10 and Chrome: Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by alampros** [comment]
I'm going to close this as you are on a really old version. Please feel free to fork it and modify your own version to support older react versions.
