### ISSUE TITLE
Confetti now become the target of pointer events

### ISSUE THREAD

**Issue by alan97** [alampros/react-confetti#63]
In react-confetti 2.4.1 we apply `pointer-events: none` to the confetti (https://github.com/alampros/react-confetti/blob/v2.4.1/src/react-confetti.js#L105) but we don't do it anymore since 2.5.0 (https://github.com/alampros/react-confetti/blob/v2.5.0/src/ReactConfetti.tsx#L32). This has caused a production issue where things beneath the confetti is not clickable.

Is this an intentional change? Do we have a lot of use cases where we want the confetti to be the target of a pointer event?

**Comment by alampros** [comment]
Oh no! Sorry to hear this caused you some troubles. It was not an intentional change – probably an accidental commit when I was working on the [mouse rain demo](https://alampros.github.io/react-confetti/?path=/story/props-demos--mouse-rain).
