### ISSUE TITLE
when using drawShape, you can't use more than one image without flickering

### ISSUE THREAD

**Issue by sankho** [alampros/react-confetti#67]
I tried to randomize which shapes appear when calling `drawShape` but if I use any randomness it'll redraw which image I chose from the start.

Would be nicer I think if you can add `ParticleShape` values and have callbacks attached to that, or adjust the `this` context to also include a numeric ID (I tried tracking using `this` as a key value in a dictionary and that didn't work either)

**Comment by AlexLerman** [comment]
Hey @sankho I think I may have found a solution to your problem. 

Inside your component, `this` is getting overwritten, so it's not tracking with the individual particles. 

Pull your drawShape function out of the component context and now `this` will refer to the same context as the particle. Then you can reassign variables or generate new ones:

```
function draw(ctx) {
  function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min)) + min;
  }
  if (!this.newRan) {
    this.w = getRandomInt(10, 30);
    this.h = getRandomInt(10, 30);
    this.newRan = true;
  }
  ctx.fillRect(-this.w / 2, -this.h / 2, this.w, this.h);
  ctx.closePath();
  ctx.restore();
}

class Woo extends React.Component {

  render() {
    return (
        <Confetti
          gravity={0.06}
          numberOfPieces={60}
          drawShape={draw}
        />
    )
  }
}
```

the newRan variable makes sure it's not reassigning the height and width at every update.
