### ISSUE TITLE
Confetti looks too thin on mobile (confetti shape based on window height, width)

### ISSUE THREAD

**Issue by suzyng83209** [alampros/react-confetti#7]
Individual confetti pieces are dependent on the window's width/height. This makes it look skewed on mobile or when the window is pulled into different aspect ratios.
![capture](https://cloud.githubusercontent.com/assets/22352112/23141425/9cee9444-f76b-11e6-924d-c0a8ea3db40f.PNG)
Confetti pieces should optimally be rendered independent of the size/aspect ratio of the canvas?

**Comment by alampros** [comment]
This is because you need to adjust the size props when the window is resized. See [this comment](https://github.com/alampros/react-confetti/issues/3#issuecomment-270460745) for a solution.
