### ISSUE TITLE
5.0.0 Warning: ReactConfetti: getSnapshotBeforeUpdate() should be used with componentDidUpdate().

### ISSUE THREAD

**Issue by wheeler** [alampros/react-confetti#73]
😞 Well looks like I didn't test enough. When using 5.0.0 in my project I get...

`Warning: ReactConfetti: getSnapshotBeforeUpdate() should be used with componentDidUpdate(). This component defines getSnapshotBeforeUpdate() only.`

I can look in to fixing (probably just changing the functionality from `getSnapshotBeforeUpdate` to `componentDidUpdate`).

@alampros FYI. It's only a warning so probably not worth looking in to unpublishing 5.0.0. It could be asserted "it works but gives warnings that will be fixed in 5.0.1". The minor bummer might be that if the solution doesn't require `16.3` the 5.0.0 breaking change bump would have been unnecessary.

**Comment by alampros** [comment]
I don't think it even needs a snapshot. We're just shipping the changed confetti options to the internal confetti class and that isn't very taxing.

**Comment by wheeler** [comment]
Nice.
