### ISSUE TITLE
Resizing during render

### ISSUE THREAD

**Issue by jnnkB** [alampros/react-confetti#74]
This library really works and looks great!

Unfortunately it does not resize while the confetti is rendered.
<img width="1197" alt="screenshot" src="https://user-images.githubusercontent.com/29376715/67389089-2cfc1f00-f59a-11e9-853c-faa81faa9155.png"> Here I enlarged the window after loading the page. You can see that the confetti is only rendered on the left side.
 
Is there a way to get that to work? 

Here is my current test project:
[test.zip](https://github.com/alampros/react-confetti/files/3762057/test.zip)

**Comment by alampros** [comment]
Thanks, @jnnkB !

The size props (`width` and `height`) are left up to you to manage. [The docs](https://github.com/alampros/react-confetti#use) have instructions and there are [many](https://github.com/streamich/react-use/blob/master/docs/useWindowSize.md), [many](https://github.com/rehooks/component-size), [other libraries](https://github.com/FezVrasta/react-resize-aware) to manage element/window dimensions.

**Comment by jnnkB** [comment]
I already used react-window-size to manage them my self. But even though this works when the confetti is not visible, it seem not to render particles outside the former visible  area, when resized after the first particles showed up. You can see the problem in the following gif. I use the code from [the docs](https://github.com/alampros/react-confetti#use) and only added `recycle={false}`.
![out](https://user-images.githubusercontent.com/29376715/68038163-9c27f080-fcc9-11e9-8079-33107514a8a2.gif)
Is it possible to get particles outside the area displayed when to confetti started?
