### ISSUE TITLE
Stop after x seconds

### ISSUE THREAD

**Issue by VictorBaudot** [alampros/react-confetti#92]
How to make it run during x seconds?

**Comment by coderinblack08** [comment]
Use `useState` and set a variable, then in `useEffect` set a timeout. I'm pretty sure there isn't a built-in method that handles this.

**Comment by cameronmoreau** [comment]
If you're using `react-use` (per the README example), [useTimeout](https://github.com/streamich/react-use/blob/master/docs/useTimeout.md) will do the trick 🎉 

```jsx
import React from 'react'
import {useWindowSize, useTimeout} from 'react-use'
import Confetti from 'react-confetti'

export default () => {
  const { width, height } = useWindowSize()
  const [isComplete] = useTimeout(4000);

  return (
    <Confetti
      width={width}
      height={height}
      recycle={!isComplete()}
    />
  )
}
```

**Comment by coderinblack08** [comment]
@cameronmoreau Sounds Great

**Comment by addamove** [comment]
I'm thinking we need to add this to doc. I found similar struggle
