### ISSUE TITLE
Confetti lagging heavily on iOS device

### ISSUE THREAD

**Issue by Rabter1** [alampros/react-confetti#95]
I am using react-confetti inside of the Ionic-Framework. 
It worked just fine since i noticed today, that the animation is lagging heavily on Iphone 11. 
(Low FPS --> slow motion falling)
CPU is chillin at arround 4%

I am using version: "react-confetti": "^6.0.0",

I do not remember updating any packages in my project. Thats why i believe the issue could be associated with iOS version...
Currently i am running iOS 14.0.1
When i stop the animation and more and more confetti fall out of the screen the animation speeds up.

Are ther any known issues / limitations on iOS/Safari that restrict the computational power of the Iphone on websites?
Is it even an issue with iOS or this plugin?

Confetti settings are default. 
On PC the confetti runs just fine. Its only the physical iOS device.

**Comment by Rabter1** [comment]
Update:  
I updated the iOS to 14.2 and the issue remains. 

I also visited the Demo of this plugin with my phone: https://alampros.github.io/react-confetti
It is also lagging which indicates, that its not my application which causes the issue.

It looks like its an issue in combination with iOS devices maybe since iOS 14 
To confirm,  i visited the mentioned demo with my old Ipad mini 2 -- iOS 12.4.5
And indeed it runs way smoother on the old device / iOS version

**Comment by Rabter1** [comment]
Update:
Okay never mind. 
I asked a friend to confirm this for me on his iOS device. 
He didnt experience this issue so it was sure its just my device... 

After experimenting i noticed that i had energy saving mode activated. 

After disabling energy saving mode the issue is gone. iOS seems to limit the frames per second when this mode is activated
Totally my fault. 

This issue can be closed:
But still it behaves a littel bit awkward.
**Expected:**
The animation is the same with dropped frames
**Actual behaviour**
The animation is slowed down significantly because there are less frames per second available and all frames are still displayed instead of dropped.

**Comment by alampros** [comment]
Sorry to hear it was slow. Unfortunately, there's not much to be done about this. Since the frame rate is based on the [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) API, it is working as expected.
