### ISSUE TITLE
Cannot use react-confetti in React Native after installation - invariant violation

### ISSUE THREAD

**Issue by plnii** [alampros/react-confetti#98]
Adding <Confetti /> to a screen prompts this error. No workaround available. Any thoughts?
 
Invariant Violation: View config getter callback for component `canvas` must be a function (received `undefined`). Make sure to start component names with a capital letter.

**Comment by lokeshozloits** [comment]
I am also facing same issue when using in react native

Invariant Violation: View config getter callback for component `canvas` must be a function (received `undefined`). Make sure to start component names with a capital letter.

**Comment by ChrisBurgdorff** [comment]
Same here, what the fuck?
